import i18next from 'i18next';

// Governorate mappings
export const governorateMap = {
    'cairo': { en: 'Cairo', ar: 'القاهرة' },
    'giza': { en: 'Giza', ar: 'الجيزة' },
    'alexandria': { en: 'Alexandria', ar: 'الإسكندرية' },
    'dakahlia': { en: 'Dakahlia', ar: 'الدقهلية' },
    'red_sea': { en: 'Red Sea', ar: 'البحر الأحمر' },
    'beheira': { en: 'Beheira', ar: 'البحيرة' },
    'faiyum': { en: 'Faiyum', ar: 'الفيوم' },
    'gharbia': { en: 'Gharbia', ar: 'الغربية' },
    'ismailia': { en: 'Ismailia', ar: 'الإسماعيلية' },
    'monufia': { en: 'Monufia', ar: 'المنوفية' },
    'minya': { en: 'Minya', ar: 'المنيا' },
    'qalyubia': { en: 'Qalyubia', ar: 'القليوبية' },
    'new_valley': { en: 'New Valley', ar: 'الوادي الجديد' },
    'suez': { en: 'Suez', ar: 'السويس' },
    'aswan': { en: 'Aswan', ar: 'أسوان' },
    'asyut': { en: 'Asyut', ar: 'أسيوط' },
    'beni_suef': { en: 'Beni Suef', ar: 'بني سويف' },
    'port_said': { en: 'Port Said', ar: 'بورسعيد' },
    'damietta': { en: 'Damietta', ar: 'دمياط' },
    'sharqia': { en: 'Sharqia', ar: 'الشرقية' },
    'south_sinai': { en: 'South Sinai', ar: 'جنوب سيناء' },
    'kafr_el_sheikh': { en: 'Kafr El Sheikh', ar: 'كفر الشيخ' },
    'matrouh': { en: 'Matrouh', ar: 'مطروح' },
    'luxor': { en: 'Luxor', ar: 'الأقصر' },
    'qena': { en: 'Qena', ar: 'قنا' },
    'north_sinai': { en: 'North Sinai', ar: 'شمال سيناء' },
    'sohag': { en: 'Sohag', ar: 'سوهاج' },
};

// City mappings
export const cityMap = {
    // Cairo cities
    'maadi': { en: 'Maadi', ar: 'المعادي' },
    'mokattam': { en: 'Mokattam', ar: 'المقطم' },
    'nasr_city': { en: 'Nasr City', ar: 'مدينة نصر' },
    'heliopolis': { en: 'Heliopolis', ar: 'مصر الجديدة' },
    'ain_shams': { en: 'Ain Shams', ar: 'عين شمس' },
    'zamalek': { en: 'Zamalek', ar: 'الزمالك' },
    'downtown': { en: 'Downtown', ar: 'وسط البلد' },
    'ramses': { en: 'Ramses', ar: 'رمسيس' },
    'bab_el_shaaria': { en: 'Bab El Shaaria', ar: 'باب الشعرية' },
    'moski': { en: 'Moski', ar: 'الموسكي' },
    'el_nozha': { en: 'El Nozha', ar: 'النزهة' },
    'roxy': { en: 'Roxy', ar: 'روكسي' },
    'mataria': { en: 'Mataria', ar: 'المطرية' },
    'el_marg': { en: 'El Marg', ar: 'المرج' },
    'zeitoun': { en: 'Zeitoun', ar: 'الزيتون' },
    'ezbet_el_nakhl': { en: 'Ezbet El Nakhl', ar: 'عزبة النخل' },
    'hadayek_el_qobbah': { en: 'Hadayek El Qobbah', ar: 'حدائق القبة' },
    'old_cairo': { en: 'Old Cairo', ar: 'مصر القديمة' },
    'sayeda_zeinab': { en: 'Sayeda Zeinab', ar: 'السيدة زينب' },
    'shubra': { en: 'Shubra', ar: 'شبرا' },
    'helwan': { en: 'Helwan', ar: 'حلوان' },
    'st_may': { en: '15 May', ar: '15 مايو' },
    'new_cairo': { en: 'New Cairo', ar: 'القاهرة الجديدة' },
    'rehab_city': { en: 'Rehab City', ar: 'مدينة الرحاب' },
    'madinaty': { en: 'Madinaty', ar: 'مدينتي' },
    'sheraton': { en: 'Sheraton', ar: 'شيراتون' },
    'agakhan': { en: 'Agakhan', ar: 'أغاخان' },
    'ekhsas': { en: 'Ekhsas', ar: 'الاخصاص' },
    'amerya': { en: 'Amerya', ar: 'الأميرية' },
    'tahrir': { en: 'Tahrir', ar: 'التحرير' },
    'helmiya': { en: 'Helmiya', ar: 'الحلمية' },
    'tenth_district': { en: 'Tenth District', ar: 'الحي العاشر' },
    'khalfawy': { en: 'Khalfawy', ar: 'الخلفاوي' },
    'khalifa_mamoun': { en: 'Khalifa Mamoun', ar: 'خليفة المأمون' },
    'demerdash': { en: 'Demerdash', ar: 'الدمرداش' },
    'sawah': { en: 'Sawah', ar: 'السواح' },
    'sharabia': { en: 'Sharabia', ar: 'الشرابية' },
    'shorouk': { en: 'Shorouk', ar: 'الشروق' },
    'daher': { en: 'Daher', ar: 'الظاهر' },
    'abbassia': { en: 'Abbassia', ar: 'العباسية' },
    'fosat': { en: 'Fosat', ar: 'الفسطاط' },
    'katameya': { en: 'Katameya', ar: 'القطامية' },
    'korba': { en: 'Korba', ar: 'الكوربة' },
    'almazah': { en: 'Almazah', ar: 'ألماظة' },
    'merghany': { en: 'Merghany', ar: 'الميرغني' },
    'maassara': { en: 'Maassara', ar: 'المعصرة' },
    'maqrizi': { en: 'Maqrizi', ar: 'المقريزي' },
    'manyal': { en: 'Manyal', ar: 'المنيل' },
    'meriland': { en: 'Meriland', ar: 'ميريلاند' },
    'meray': { en: 'Meray', ar: 'مري' },
    'ahly_club': { en: 'Ahly Club', ar: 'النادي الأهلي' },
    'nozha': { en: 'Nozha', ar: 'النزهة' },
    'helal': { en: 'Helal', ar: 'الهلال' },
    'waha': { en: 'Waha', ar: 'الواحة' },
    'wayli': { en: 'Wayli', ar: 'الوايلي' },
    'badr': { en: 'Badr', ar: 'مدينة بدر' },
    'triumph': { en: 'Triumph', ar: 'تريومف' },
    'gesr_suez': { en: 'Gesr Suez', ar: 'جسر السويس' },
    'hadayek_zaitoun': { en: 'Hadayek Zaitoun', ar: 'حدائق الزيتون' },
    'hadayek_maadi': { en: 'Hadayek Maadi', ar: 'حدائق المعادي' },
    'helmiyet_el_zaitoun': { en: 'Helmiyet El Zaitoun', ar: 'حلمية الزيتون' },
    'hamamat_qobbah': { en: 'Hamamat Qobbah', ar: 'حمامات القبة' },
    'dar_elsalam': { en: 'Dar Elsalam', ar: 'دار السلام' },
    'st_fatima': { en: 'St Fatima', ar: 'سانت فاطيما' },
    'saray_el_qobbah': { en: 'Saray El Qobbah', ar: 'سراي القبة' },
    'city_stars': { en: 'City Stars', ar: 'سيتي ستارز' },
    'sakr_quraish': { en: 'Sakr Quraish', ar: 'صقر قريش' },
    'salah_salem': { en: 'Salah Salem', ar: 'صلاح سالم' },
    'carrefour_maadi': { en: 'Carrefour Maadi', ar: 'كارفور المعادي' },
    'monshiyet_el_sadr': { en: 'Monshiyet El Sadr', ar: 'منشية الصدر' },
    'shams_club': { en: 'Shams Club', ar: 'نادي الشمس' },
    'bab_ellouq': { en: 'Bab Ellouq', ar: 'باب اللوق' },
    'zahraa_maadi': { en: 'Zahraa Maadi', ar: 'زهراء المعادي' },
    'fifth_settlement': { en: 'Fifth Settlement', ar: 'التجمع الخامس' },

    // Giza cities
    'dokki': { en: 'Dokki', ar: 'الدقي' },
    'mohandessin': { en: 'Mohandessin', ar: 'المهندسين' },
    'agouza': { en: 'Agouza', ar: 'العجوزة' },
    'haram': { en: 'Haram', ar: 'الهرم' },
    'faisal': { en: 'Faisal', ar: 'فيصل' },
    'october_city': { en: 'October City', ar: 'مدينة 6 أكتوبر' },
    'th_october': { en: '6 October', ar: '6 اكتوبر' },
    'sheikh_zayed_city': { en: 'Sheikh Zayed City', ar: 'مدينة الشيخ زايد' },
    'omrania': { en: 'Omrania', ar: 'العمرانية' },
    'omrania_extra': { en: 'Omrania', ar: 'العمرانية' },
    'warraq': { en: 'Warraq', ar: 'الوراق' },
    'warraq_extra': { en: 'Warraq', ar: 'الوراق' },
    'osim': { en: 'Osim', ar: 'أوسيم' },
    'osim_extra': { en: 'Osim', ar: 'أوسيم' },
    'kerdasa': { en: 'Kerdasa', ar: 'مركز كرداسة' },
    'hawamdeya': { en: 'Hawamdeya', ar: 'الحوامدية' },
    'badrashin': { en: 'Badrashin', ar: 'البدرشين' },
    'ayyat': { en: 'Ayyat', ar: 'مركز العياط' },
    'ayyat_extra': { en: 'Ayyat', ar: 'العياط' },
    'saf': { en: 'Saf', ar: 'الصف' },
    'atfih': { en: 'Atfih', ar: 'مركز أطفيح' },
    'mansheyat_al_qanater': { en: 'Mansheyat Al Qanater', ar: 'مركز منشأة القناطر' },
    'abu_el_nomros': { en: 'Abu El Nomros', ar: 'مركز أبو النمرس' },
    'hadayek_ahram': { en: 'Hadayek Ahram', ar: 'حدائق الأهرام' },
    'hadayek_ahram_extra': { en: 'Hadayek Ahram', ar: 'هضبة الاهرام' },
    'imbaba': { en: 'Imbaba', ar: 'إمبابة' },
    'boulaq_dakrour': { en: 'Boulaq Dakrour', ar: 'بولاق الدكرور' },
    'ard_ellawa': { en: 'Ard Ellawa', ar: 'أرض اللواء' },
    'arkan_mall': { en: 'Arkan Mall', ar: 'أركان مول' },
    'bahr_aazam': { en: 'Bahr Aazam', ar: 'البحر الأعظم' },
    'hosary': { en: 'Hosary', ar: 'الحصري' },
    'sheikh_zayed': { en: 'Sheikh Zayed', ar: 'الشيخ زايد' },
    'talbia': { en: 'Talbia', ar: 'الطالبية' },
    'smart_village': { en: 'Smart Village', ar: 'القرية الذكية' },
    'kit_kat': { en: 'Kit Kat', ar: 'كيت كات' },
    'lobini': { en: 'Lobini', ar: 'اللبيني' },
    'maryoutiya': { en: 'Maryoutiya', ar: 'المريوطية' },
    'mounib': { en: 'Mounib', ar: 'المنيب' },
    'mounira': { en: 'Mounira', ar: 'المنيرة' },
    'bashtil': { en: 'Bashtil', ar: 'بشتيل' },
    'beverly_hills': { en: 'Beverly Hills', ar: 'بيفرلي هيلز' },
    'tarsa': { en: 'Tarsa', ar: 'ترسا' },
    'khatem_morsalin': { en: 'Khatem Morsalin', ar: 'خاتم المرسلين' },
    'zayed': { en: 'Zayed', ar: 'زايد' },
    'kafr_taharmes': { en: 'Kafr Taharmes', ar: 'كفر طهيرمس' },
    'court_yard': { en: 'Court Yard', ar: 'كورت يارد' },
    'moussadak': { en: 'Moussadak', ar: 'مصدق' },
    'lebanon_square': { en: 'Lebanon Square', ar: 'ميدان لبنان' },
    'new_giza': { en: 'New Giza', ar: 'نيو جيزة' },
    'gezira_plaza': { en: 'Gezira Plaza', ar: 'جزيرة بلازا' },
    'park_street': { en: 'Park Street', ar: 'بارك ستريت' },
    'cairo_medical': { en: 'Cairo Medical', ar: 'كايرو ميديكال' },

    // Alexandria cities
    'montaza': { en: 'Montaza', ar: 'المنتزه' },
    'smouha': { en: 'Smouha', ar: 'سموحة' },
    'siouf': { en: 'Siouf', ar: 'السيوف' },
    'siouf_extra': { en: 'Siouf', ar: 'سيوف' },
    'asafra': { en: 'Asafra', ar: 'العصافرة' },
    'labban': { en: 'Labban', ar: 'اللبان' },
    'raml': { en: 'Raml', ar: 'الرمل' },
    'shatby': { en: 'Shatby', ar: 'الشاطبي' },
    'azarita': { en: 'Azarita', ar: 'الأزاريطة' },
    'camp_caesar': { en: 'Camp Caesar', ar: 'كامب شيزار' },
    'ibrahimia': { en: 'Ibrahimia', ar: 'الإبراهيمية' },
    'kom_el_deka': { en: 'Kom El Deka', ar: 'كوم الدكة' },
    'maharam_bek': { en: 'Maharam Bek', ar: 'محرم بك' },
    'east_alexandria': { en: 'East Alexandria', ar: 'شرق الإسكندرية' },
    'lauren': { en: 'Lauren', ar: 'لوران' },
    'zizinia': { en: 'Zizinia', ar: 'زيزينيا' },
    'bolkly': { en: 'Bolkly', ar: 'بولكلي' },
    'fleming': { en: 'Fleming', ar: 'فلمنج' },
    'shots': { en: 'Shots', ar: 'شوتس' },
    'san_stefano': { en: 'San Stefano', ar: 'سان ستيفانو' },
    'kafr_abdo': { en: 'Kafr Abdo', ar: 'كفر عبده' },
    'sidi_gaber': { en: 'Sidi Gaber', ar: 'سيدي جابر' },
    'sidi_bishr': { en: 'Sidi Bishr', ar: 'سيدي بشر' },
    'bitash': { en: 'Bitash', ar: 'البيطاش' },
    'hanoville': { en: 'Hanoville', ar: 'الهانوفيل' },
    'amreya': { en: 'Amreya', ar: 'العامرية' },
    'km_21': { en: 'KM 21', ar: 'الكيلو 21' },
    'abou_qir': { en: 'Abou Qir', ar: 'أبو قير' },
    'borg_el_arab': { en: 'Borg El Arab', ar: 'برج العرب' },
    'wardian': { en: 'Wardian', ar: 'الورديان' },
    'falaki': { en: 'Falaki', ar: 'الفلكي' },
    'gomrok': { en: 'Gomrok', ar: 'الجمرك' },
    'miami': { en: 'Miami', ar: 'ميامي' },
    'mandara': { en: 'Mandara', ar: 'المندرة' },
    'manshia': { en: 'Manshia', ar: 'المنشية' },
    'victoria': { en: 'Victoria', ar: 'فيكتوريا' },
    'agami': { en: 'Agami', ar: 'العجمي' },
    'bab_sharq': { en: 'Bab Sharq', ar: 'باب شرق' },
    'bahary': { en: 'Bahary', ar: 'بحري' },
    'gleem': { en: 'Gleem', ar: 'جليم' },
    'gianaclis': { en: 'Gianaclis', ar: 'جناكليس' },
    'rashdy': { en: 'Rashdy', ar: 'رشدي' },
    'sporting': { en: 'Sporting', ar: 'سبورتنج' },
    'mahatet_el_raml': { en: 'Mahatet El Raml', ar: 'محطة الرمل' },
    'mostafa_kamel': { en: 'Mostafa Kamel', ar: 'مصطفى كامل' },
    'mamoura': { en: 'Mamoura', ar: 'المعمورة' },
    'matoubes': { en: 'Matoubes', ar: 'مطوبس' },
    'askout': { en: 'Askout', ar: 'اسكوت' },
    'abu_youssef': { en: 'Abu Youssef', ar: 'ابو يوسف' },

    // Dakahlia cities
    'mansoura': { en: 'Mansoura', ar: 'المنصورة' },
    'talkha': { en: 'Talkha', ar: 'طلخا' },
    'mit_ghamr': { en: 'Mit Ghamr', ar: 'ميت غمر' },
    'belqas': { en: 'Belqas', ar: 'بلقاس' },
    'aga': { en: 'Aga', ar: 'أجا' },
    'sinbillawin': { en: 'Sinbillawin', ar: 'السنبلاوين' },
    'sherbin': { en: 'Sherbin', ar: 'شربين' },
    'beni_ebeid': { en: 'Beni Ebeid', ar: 'بني عبيد' },
    'dekernes': { en: 'Dekernes', ar: 'دكرنس' },
    'samanoud': { en: 'Samanoud', ar: 'سمنود' },
    'samannoud': { en: 'Samanoud', ar: 'سمنود' },
    'delta': { en: 'Delta', ar: 'دلتا' },
    'menia_el_nasr': { en: 'Menia El Nasr', ar: 'منية النصر' },
    'el_manzala': { en: 'El Manzala', ar: 'المنزلة' },
    'mit_salsil': { en: 'Mit Salsil', ar: 'ميت سلسيل' },
    'gamasa': { en: 'Gamasa', ar: 'جمصة' },
    'nabaroh': { en: 'Nabaroh', ar: 'نبروه' },
    'el_kurdi': { en: 'El Kurdi', ar: 'الكردي' },
    'mahalet_demna': { en: 'Mahalet Demna', ar: 'محلة دمنة' },
    'gamalia': { en: 'Gamalia', ar: 'الجمالية' },

    // Red Sea cities
    'hurghada': { en: 'Hurghada', ar: 'الغردقة' },
    'marsa_alam': { en: 'Marsa Alam', ar: 'مرسى علم' },
    'ras_ghareb': { en: 'Ras Ghareb', ar: 'رأس غارب' },
    'safaga': { en: 'Safaga', ar: 'سفاجا' },
    'ain_sokhna': { en: 'Ain Sokhna', ar: 'العين السخنة' },

    // Beheira cities
    'damanhour': { en: 'Damanhour', ar: 'دمنهور' },
    'kafr_el_dawar': { en: 'Kafr El Dawar', ar: 'كفر الدوار' },
    'abu_hummus': { en: 'Abu Hummus', ar: 'أبو حمص' },
    'hosh_essa': { en: 'Hosh Essa', ar: 'حوش عيسى' },
    'hosh_essa_extra': { en: 'Hosh Essa', ar: 'حوش عيسى' },
    'delengat': { en: 'Delengat', ar: 'الدلنجات' },
    'itay_el_barud': { en: 'Itay El Barud', ar: 'إيتاي البارود' },
    'shubrakhit': { en: 'Shubrakhit', ar: 'شبراخيت' },
    'edko': { en: 'Edko', ar: 'إدكو' },
    'rashid': { en: 'Rashid', ar: 'رشيد' },
    'rahmaniya': { en: 'Rahmaniya', ar: 'الرحمانية' },
    'noubaria': { en: 'Noubaria', ar: 'النوبارية' },
    'kom_hamada': { en: 'Kom Hamada', ar: 'كوم حمادة' },
    'abu_el_matamir': { en: 'Abu El Matamir', ar: 'أبو المطامير' },
    'wadi_el_natrun': { en: 'Wadi El Natrun', ar: 'وادي النطرون' },
    'advina': { en: 'Advina', ar: 'أدفينا' },

    // Faiyum cities
    'faiyum_city': { en: 'Faiyum City', ar: 'مدينة الفيوم' },
    'sinnuris': { en: 'Sinnuris', ar: 'سنورس' },
    'etsa': { en: 'Etsa', ar: 'إطسا' },
    'abubakk': { en: 'Abubakk', ar: 'أبشواي' },
    'mosalla': { en: 'Mosalla', ar: 'المسلة' },
    'tamiya': { en: 'Tamiya', ar: 'طامية' },

    // Gharbia cities
    'tanta': { en: 'Tanta', ar: 'طنطا' },
    'mahalla': { en: 'Mahalla', ar: 'المحلة الكبرى' },
    'el_mahalla_el_kubra': { en: 'El Mahalla El Kubra', ar: 'المحلة الكبرى' },
    'zefta': { en: 'Zefta', ar: 'زفتى' },
    'zefta_extra': { en: 'Zefta', ar: 'زفتي' },
    'kafr_el_zayat': { en: 'Kafr El Zayat', ar: 'كفر الزيات' },
    'basion': { en: 'Basion', ar: 'بسيون' },
    'qutour': { en: 'Qutour', ar: 'قطور' },
    'santah': { en: 'Santah', ar: 'السنطة' },

    // Ismailia cities
    'ismailia_city': { en: 'Ismailia City', ar: 'مدينة الإسماعيلية' },
    'qantera_west': { en: 'Qantera West', ar: 'القنطره غرب' },
    'tal_el_kebir': { en: 'Tal El Kebir', ar: 'التل الكبير' },
    'el_tal_el_kebir': { en: 'El Tal El Kebir', ar: 'التل الكبير' },
    'fayed': { en: 'Fayed', ar: 'فايد' },
    'qantera': { en: 'Qantera', ar: 'القنطرة' },
    'qantera_east': { en: 'Qantera East', ar: 'القنطره شرق' },

    // Monufia cities
    'shebin_el_kom': { en: 'Shebin El Kom', ar: 'شبين الكوم' },
    'menouf': { en: 'Menouf', ar: 'منوف' },
    'ashmoun': { en: 'Ashmoun', ar: 'أشمون' },
    'bagour': { en: 'Bagour', ar: 'الباجور' },
    'sadat_city': { en: 'Sadat City', ar: 'مدينة السادات' },
    'quesna': { en: 'Quesna', ar: 'قويسنا' },
    'shohada': { en: 'Shohada', ar: 'الشهداء' },
    'el_shohada': { en: 'Shohada', ar: 'الشهداء' },
    'baranya': { en: 'Baranya', ar: 'برانية' },
    'sadat': { en: 'Sadat', ar: 'السادات' },
    'begeirm': { en: 'Begeirm', ar: 'بجيرم' },
    'mit_bere': { en: 'Mit Bere', ar: 'ميت برة' },
    'tala': { en: 'Tala', ar: 'تلا' },
    'berket_el_sabaa': { en: 'Berket El Sabaa', ar: 'بركة السبع' },
    'may': { en: 'May', ar: 'الماي' },

    // Minya cities
    'minya_city': { en: 'Minya City', ar: 'مدينة المنيا' },
    'malawi': { en: 'Malawi', ar: 'ملوي' },
    'maghagha': { en: 'Maghagha', ar: 'مغاغة' },
    'beni_mazar': { en: 'Beni Mazar', ar: 'بني مزار' },
    'samalout': { en: 'Samalout', ar: 'سمالوط' },
    'abu_qurqas': { en: 'Abu Qurqas', ar: 'أبو قرقاص' },
    'deir_mawas': { en: 'Deir Mawas', ar: 'دير مواس' },
    'el_edwa': { en: 'El Edwa', ar: 'العدوة' },
    'matai': { en: 'Matai', ar: 'مطاي' },

    // Qalyubia cities
    'banha': { en: 'Banha', ar: 'بنها' },
    'qalyub': { en: 'Qalyub', ar: 'قليوب' },
    'shubra_el_kheima': { en: 'Shubra El Kheima', ar: 'شبرا الخيمة' },
    'kafr_shukr': { en: 'Kafr Shukr', ar: 'كفر شكر' },
    'tukh': { en: 'Tukh', ar: 'طوخ' },
    'shibin_el_qanater': { en: 'Shibin El Qanater', ar: 'شبين القناطر' },
    'khanka': { en: 'Khanka', ar: 'الخانكة' },
    'el_khanka': { en: 'El Khanka', ar: 'القناطر الخيرية' },
    'qaha': { en: 'Qaha', ar: 'قها' },
    'obour_city': { en: 'Obour City', ar: 'مدينة العبور' },
    'khusus': { en: 'Khosus', ar: 'الخصوص' },
    'qanatir': { en: 'Qanatir', ar: 'القناطر' },
    'abour': { en: 'Abour', ar: 'العبور' },

    // New Valley cities
    'kharga': { en: 'Kharga', ar: 'الخارجة' },
    'dakhla': { en: 'Dakhla', ar: 'الداخلة' },
    'paris': { en: 'Paris', ar: 'باريس' },

    // Suez cities
    'suez_city': { en: 'Suez City', ar: 'مدينة السويس' },
    'arbaeen': { en: 'Arbaeen', ar: 'الأربعين' },
    'suez_district': { en: 'Suez District', ar: 'حي السويس' },
    'attaka_district': { en: 'Attaka District', ar: 'حي عتاقة' },
    'el_ganayen_district': { en: 'El Ganayen District', ar: 'حي الجناين' },
    'green_island': { en: 'Green Island', ar: 'الجزيرة الخضراء' },
    'shatt': { en: 'Shatt', ar: 'الشط' },
    'houd_el_dars': { en: 'Houd El Dars', ar: 'حوض الدرس' },
    'port_tawfik': { en: 'Port Tawfik', ar: 'بورتوفيق' },
    'craftsmen_city': { en: 'Craftsmen City', ar: 'مدينة الحرفيين' },
    'el_sabah': { en: 'El Sabah', ar: 'الصباح' },
    'el_amal': { en: 'El Amal', ar: 'الأمل' },
    'mubarak': { en: 'Mubarak', ar: 'مبارك' },
    'cooperations': { en: 'Cooperations', ar: 'التعاونيات' },
    'salam': { en: 'Salam', ar: 'السلام' },
    'nour': { en: 'Nour', ar: 'النور' },
    'ferdous': { en: 'Ferdous', ar: 'الفردوس' },
    'tawfiqia': { en: 'Tawfiqia', ar: 'التوفيقية' },
    'arab_el_maamal_area': { en: 'Arab El Maamal Area', ar: 'منطقة عرب المعمل' },
    'arbaeen_district': { en: 'Arbaeen District', ar: 'حي الأربعين' },

    // Aswan cities
    'aswan_city': { en: 'Aswan City', ar: 'أسوان' },
    'kom_ombo': { en: 'Kom Ombo', ar: 'كوم أمبو' },
    'daraw': { en: 'Daraw', ar: 'دراو' },
    'new_aswan_city': { en: 'New Aswan City', ar: 'مدينة أسوان الجديدة' },
    'edfu_center': { en: 'Edfu Center', ar: 'مركز إدفو' },
    'aswan_center': { en: 'Aswan Center', ar: 'مركز أسوان' },
    'abu_simbel_center': { en: 'Abu Simbel Center', ar: 'مركز أبو سمبل' },
    'daraw_center': { en: 'Daraw Center', ar: 'مركز دراو' },
    'kom_ombo_center': { en: 'Kom Ombo Center', ar: 'مركز كوم أمبو' },
    'nasr_el_nuba_center': { en: 'Nasr El Nuba Center', ar: 'مركز نصر النوبة' },

    // Asyut cities
    'asyut_city': { en: 'Asyut City', ar: 'مدينة أسيوط' },
    'abu_tis': { en: 'Abu Tis', ar: 'ابو تيج' },
    'nomiss': { en: 'Nomiss', ar: 'النواميس' },
    'abnub': { en: 'Abnub', ar: 'أبنوب' },
    'dayrout': { en: 'Dayrout', ar: 'ديروط' },
    'manfalut': { en: 'Manfalut', ar: 'منفلوط' },

    // Beni Suef cities
    'beni_suef_city': { en: 'Beni Suef City', ar: 'مدينة بني سويف' },
    'wasta': { en: 'Wasta', ar: 'الواسطه' },
    'el_wasta': { en: 'El Wasta', ar: 'الواسطى' },
    'naser': { en: 'Naser', ar: 'ناصر' },
    'beba': { en: 'Beba', ar: 'بيبا' },
    'fashn': { en: 'Fashn', ar: 'الفشن' },

    // Port Said cities
    'port_said_city': { en: 'Port Said City', ar: 'مدينة بورسعيد' },
    'port_fouad': { en: 'Port Fouad', ar: 'بورفؤاد' },
    'east_district': { en: 'East District', ar: 'حي الشرق' },
    'west_district': { en: 'West District', ar: 'حي الغرب' },

    // Damietta cities
    'damietta_city': { en: 'Damietta City', ar: 'مدينة دمياط' },
    'faraskour': { en: 'Faraskour', ar: 'فارسكور' },
    'kafr_saad': { en: 'Kafr Saad', ar: 'كفر سعد' },
    'zarqa': { en: 'Zarqa', ar: 'الزرقا' },

    // Sharqia cities
    'zagazig': { en: 'Zagazig', ar: 'الزقازيق' },
    'belbeis': { en: 'Belbeis', ar: 'بلبيس' },
    'abu_kabir': { en: 'Abu Kabir', ar: 'أبو كبير' },
    'kafr_saqr': { en: 'Kafr Saqr', ar: 'كفر صقر' },
    'menia_el_qamh': { en: 'Menia El Qamh', ar: 'منيا القمح' },
    'menia_el_qamh_extra': { en: 'Menia El Qamh', ar: 'منيا القمح' },
    'faques': { en: 'Faques', ar: 'فاقوس' },
    'tenth_of_ramadan_city': { en: 'Tenth of Ramadan City', ar: 'مدينة العاشر من رمضان' },
    'abu_hammad': { en: 'Abu Hammad', ar: 'ابو حماد' },
    'salheya': { en: 'Salheya', ar: 'الصالحية الجديدة' },
    'new_salheya': { en: 'New Salheya', ar: 'الصالحية الجديدة' },
    'qanayat': { en: 'Qanayat', ar: 'القنايات' },
    'hehya': { en: 'Hehya', ar: 'ههيا' },
    'ibrahimia_sharqia': { en: 'Ibrahimia Sharqia', ar: 'الإبراهيمية' },
    'awlad_saqr': { en: 'Awlad Saqr', ar: 'أولاد صقر' },
    'husseiniya': { en: 'Husseiniya', ar: 'الحسينية' },
    'deirb_negm': { en: 'Deirb Negm', ar: 'ديرب نجم' },
    'el_qurin': { en: 'El Qurin', ar: 'القرين' },
    'mashtool_el_souk': { en: 'Mashtool El Souk', ar: 'مشتول السوق' },
    'abu_hamad': { en: 'Abu Hamad', ar: 'أبو حماد' },

    // South Sinai cities
    'sharm_el_sheikh': { en: 'Sharm El Sheikh', ar: 'شرم الشيخ' },
    'dahab': { en: 'Dahab', ar: 'دهب' },
    'nuweiba': { en: 'Nuweiba', ar: 'نويبع' },

    // Kafr El Sheikh cities
    'kafr_el_sheikh_city': { en: 'Kafr El Sheikh City', ar: 'مدينة كفر الشيخ' },
    'desouk': { en: 'Desouk', ar: 'دسوق' },
    'sidi_salem': { en: 'Sidi Salem', ar: 'سيدي سالم' },
    'fuwa': { en: 'Fuwa', ar: 'فوة' },

    // Matrouh cities
    'marsa_matrouh': { en: 'Marsa Matrouh', ar: 'مرسى مطروح' },
    'north_coast': { en: 'North Coast', ar: 'الساحل الشمالي' },
    'hacienda': { en: 'Hacienda', ar: 'هاسيندا' },
    'amwaj': { en: 'Amwaj', ar: 'أمواج' },
    'hamam': { en: 'Hamam', ar: 'الحمام' },
    'nagila': { en: 'Nagila', ar: 'النجيلة' },
    'el_alamein': { en: 'El Alamein', ar: 'العلمين' },
    'dabaa': { en: 'Dabaa', ar: 'الضبعة' },
    'sidi_barrani': { en: 'Sidi Barrani', ar: 'سيدي براني' },
    'salloum': { en: 'Salloum', ar: 'السلوم' },
    'siwa': { en: 'Siwa', ar: 'سيوة' },

    // Luxor cities
    'luxor_city': { en: 'Luxor City', ar: 'مدينة الأقصر' },
    'esna': { en: 'Esna', ar: 'إسنا' },
    'qurna': { en: 'Qurna', ar: 'القرنة' },

    // Qena cities
    'qena_city': { en: 'Qena City', ar: 'مدينة قنا' },
    'qift': { en: 'Qift', ar: 'قفط' },
    'qous': { en: 'Qous', ar: 'قوص' },
    'nag_hamadi': { en: 'Nag Hamadi', ar: 'نجع حمادي' },
    'deshna': { en: 'Deshna', ar: 'دشتا' },
    'naqada': { en: 'Naqada', ar: 'نقادة' },

    // North Sinai cities
    'el_arish': { en: 'El Arish', ar: 'العريش' },
    'sheikh_zuweid': { en: 'Sheikh Zuweid', ar: 'الشيخ زويد' },
    'rafah': { en: 'Rafah', ar: 'رفح' },

    // Sohag cities
    'sohag_city': { en: 'Sohag City', ar: 'مدينة سوهاج' },
    'girga': { en: 'Girga', ar: 'جرجا' },
    'tahta': { en: 'Tahta', ar: 'طهطا' },
    'asierat': { en: 'Asierat', ar: 'العسيرات' },
    'akhmim': { en: 'Akhmim', ar: 'أخميم' },

    // Additional common keys
    'ahmed_orabi': { en: 'Ahmed Orabi', ar: 'احمد عرابي' },
    'galaa': { en: 'Galaa', ar: 'الجلاء' },
    'higaz': { en: 'Higaz', ar: 'الحجاز' },
    'kasr_alainy': { en: 'Kasr Alainy', ar: 'القصر العيني' },
    'kwadi': { en: 'Kwadi', ar: 'الكوادي' },
    'corniche': { en: 'Corniche', ar: 'الكورنيش' },
    'barada': { en: 'Barada', ar: 'براده' },
};

export const getGovernorateName = (key) => {
    const lang = i18next.language?.startsWith('ar') ? 'ar' : 'en';
    if (!key) return lang === 'ar' ? 'غير متوفر' : 'N/A';
    const entry = governorateMap[key.toLowerCase()];
    if (!entry) return key;
    return typeof entry === 'string' ? entry : (entry[lang] || entry['en'] || key);
};

export const getCityName = (key) => {
    const lang = i18next.language?.startsWith('ar') ? 'ar' : 'en';
    if (!key) return lang === 'ar' ? 'غير متوفر' : 'N/A';
    const entry = cityMap[key.toLowerCase()];
    if (!entry) return key;
    return typeof entry === 'string' ? entry : (entry[lang] || entry['en'] || key);
};