// Governorate mappings
export const governorateMap = {
    'cairo': 'Cairo',
    'giza': 'Giza',
    'alexandria': 'Alexandria',
    'dakahlia': 'Dakahlia',
    'red_sea': 'Red Sea',
    'beheira': 'Beheira',
    'faiyum': 'Faiyum',
    'gharbia': 'Gharbia',
    'ismailia': 'Ismailia',
    'monufia': 'Monufia',
    'minya': 'Minya',
    'qalyubia': 'Qalyubia',
    'new_valley': 'New Valley',
    'suez': 'Suez',
    'aswan': 'Aswan',
    'asyut': 'Asyut',
    'beni_suef': 'Beni Suef',
    'port_said': 'Port Said',
    'damietta': 'Damietta',
    'sharqia': 'Sharqia',
    'south_sinai': 'South Sinai',
    'kafr_el_sheikh': 'Kafr El Sheikh',
    'matrouh': 'Matrouh',
    'luxor': 'Luxor',
    'qena': 'Qena',
    'north_sinai': 'North Sinai',
    'sohag': 'Sohag',
};

// City mappings
export const cityMap = {
    // Cairo cities
    'maadi': 'Maadi',
    'mokattam': 'Mokattam',
    'nasr_city': 'Nasr City',
    'heliopolis': 'Heliopolis',
    'ain_shams': 'Ain Shams',
    'zamalek': 'Zamalek',
    'downtown': 'Downtown',
    'ramses': 'Ramses',
    'bab_el_shaaria': 'Bab El Shaaria',
    'moski': 'Moski',
    'el_nozha': 'El Nozha',
    'roxy': 'Roxy',
    'mataria': 'Mataria',
    'el_marg': 'El Marg',
    'zeitoun': 'Zeitoun',
    'ezbet_el_nakhl': 'Ezbet El Nakhl',
    'hadayek_el_qobbah': 'Hadayek El Qobbah',
    'old_cairo': 'Old Cairo',
    'sayeda_zeinab': 'Sayeda Zeinab',
    'shubra': 'Shubra',
    'helwan': 'Helwan',
    'st_may': 'St May',
    'new_cairo': 'New Cairo',
    'rehab_city': 'Rehab City',
    'madinaty': 'Madinaty',
    'sheraton': 'Sheraton',
    'agakhan': 'Agakhan',
    'ekhsas': 'Ekhsas',
    'amerya': 'Amerya',
    'tahrir': 'Tahrir',
    'helmiya': 'Helmiya',
    'tenth_district': 'Tenth District',
    'khalfawy': 'Khalfawy',
    'khalifa_mamoun': 'Khalifa Mamoun',
    'demerdash': 'Demerdash',
    'sawah': 'Sawah',
    'sharabia': 'Sharabia',
    'shorouk': 'Shorouk',
    'daher': 'Daher',
    'abbassia': 'Abbassia',
    'fosat': 'Fosat',
    'katameya': 'Katameya',
    'korba': 'Korba',
    'almazah': 'Almazah',
    'merghany': 'Merghany',
    'maassara': 'Maassara',
    'maqrizi': 'Maqrizi',
    'manyal': 'Manyal',
    'meriland': 'Meriland',
    'meray': 'Meray',
    'ahly_club': 'Ahly Club',
    'nozha': 'Nozha',
    'helal': 'Helal',
    'waha': 'Waha',
    'wayli': 'Wayli',
    'badr': 'Badr',
    'triumph': 'Triumph',
    'gesr_suez': 'Gesr Suez',
    'hadayek_zaitoun': 'Hadayek Zaitoun',
    'hadayek_maadi': 'Hadayek Maadi',
    'helmiyet_el_zaitoun': 'Helmiyet El Zaitoun',
    'hamamat_qobbah': 'Hamamat Qobbah',
    'dar_elsalam': 'Dar Elsalam',
    'st_fatima': 'St Fatima',
    'saray_el_qobbah': 'Saray El Qobbah',
    'city_stars': 'City Stars',
    'sakr_quraish': 'Sakr Quraish',
    'salah_salem': 'Salah Salem',
    'carrefour_maadi': 'Carrefour Maadi',
    'monshiyet_el_sadr': 'Monshiyet El Sadr',
    'shams_club': 'Shams Club',
    'bab_ellouq': 'Bab Ellouq',

    // Giza cities
    'dokki': 'Dokki',
    'mohandessin': 'Mohandessin',
    'agouza': 'Agouza',
    'haram': 'Haram',
    'faisal': 'Faisal',
    'october_city': 'October City',
    'sheikh_zayed_city': 'Sheikh Zayed City',
    'omrania': 'Omrania',
    'warraq': 'Warraq',
    'osim': 'Osim',
    'kerdasa': 'Kerdasa',
    'hawamdeya': 'Hawamdeya',
    'badrashin': 'Badrashin',
    'ayyat': 'Ayyat',
    'saf': 'Saf',
    'hadayek_ahram': 'Hadayek Ahram',
    'imbaba': 'Imbaba',
    'boulaq_dakrour': 'Boulaq Dakrour',
    'ard_ellawa': 'Ard Ellawa',
    'arkan_mall': 'Arkan Mall',
    'bahr_aazam': 'Bahr Aazam',
    'hosary': 'Hosary',
    'sheikh_zayed': 'Sheikh Zayed',
    'talbia': 'Talbia',
    'smart_village': 'Smart Village',
    'kit_kat': 'Kit Kat',
    'lobini': 'Lobini',
    'maryoutiya': 'Maryoutiya',
    'mounib': 'Mounib',
    'mounira': 'Mounira',
    'bashtil': 'Bashtil',
    'beverly_hills': 'Beverly Hills',
    'tarsa': 'Tarsa',
    'khatem_morsalin': 'Khatem Morsalin',
    'zayed': 'Zayed',
    'kafr_taharmes': 'Kafr Taharmes',
    'court_yard': 'Court Yard',
    'moussadak': 'Moussadak',
    'lebanon_square': 'Lebanon Square',
    'new_giza': 'New Giza',
    'gezira_plaza': 'Gezira Plaza',
    'park_street': 'Park Street',
    'cairo_medical': 'Cairo Medical',

    // Alexandria cities
    'montaza': 'Montaza',
    'smouha': 'Smouha',
    'siouf': 'Siouf',
    'asafra': 'Asafra',
    'labban': 'Labban',
    'raml': 'Raml',
    'shatby': 'Shatby',
    'azarita': 'Azarita',
    'camp_caesar': 'Camp Caesar',
    'ibrahimia': 'Ibrahimia',
    'kom_el_deka': 'Kom El Deka',
    'maharam_bek': 'Maharam Bek',
    'east_alexandria': 'East Alexandria',
    'lauren': 'Lauren',
    'zizinia': 'Zizinia',
    'bolkly': 'Bolkly',
    'fleming': 'Fleming',
    'shots': 'Shots',
    'san_stefano': 'San Stefano',
    'kafr_abdo': 'Kafr Abdo',
    'sidi_gaber': 'Sidi Gaber',
    'sidi_bishr': 'Sidi Bishr',
    'bitash': 'Bitash',
    'hanoville': 'Hanoville',
    'amreya': 'Amreya',
    'km_21': 'KM 21',
    'abou_qir': 'Abou Qir',
    'borg_el_arab': 'Borg El Arab',
    'wardian': 'Wardian',
    'falaki': 'Falaki',
    'gomrok': 'Gomrok',
    'miami': 'Miami',
    'mandara': 'Mandara',
    'manshia': 'Manshia',
    'victoria': 'Victoria',
    'agami': 'Agami',
    'bab_sharq': 'Bab Sharq',
    'bahary': 'Bahary',
    'gleem': 'Gleem',
    'gianaclis': 'Gianaclis',
    'rashdy': 'Rashdy',
    'sporting': 'Sporting',
    'mahatet_el_raml': 'Mahatet El Raml',
    'mostafa_kamel': 'Mostafa Kamel',
    'mamoura': 'Mamoura',
    'matoubes': 'Matoubes',
    'askout': 'Askout',

    // Dakahlia cities
    'mansoura': 'Mansoura',
    'talkha': 'Talkha',
    'mit_ghamr': 'Mit Ghamr',
    'belqas': 'Belqas',
    'aga': 'Aga',
    'sinbillawin': 'Sinbillawin',
    'sherbin': 'Sherbin',
    'beni_ebeid': 'Beni Ebeid',
    'dekernes': 'Dekernes',
    'samanoud': 'Samanoud',
    'delta': 'Delta',
    'menia_el_nasr': 'Menia El Nasr',
    'el_manzala': 'El Manzala',
    'mit_salsil': 'Mit Salsil',
    'gamasa': 'Gamasa',
    'nabaroh': 'Nabaroh',
    'el_kurdi': 'El Kurdi',
    'mahalet_demna': 'Mahalet Demna',
    'gamalia': 'Gamalia',

    // Red Sea cities
    'hurghada': 'Hurghada',
    'marsa_alam': 'Marsa Alam',
    'ras_ghareb': 'Ras Ghareb',
    'safaga': 'Safaga',
    'ain_sokhna': 'Ain Sokhna',

    // Beheira cities
    'damanhour': 'Damanhour',
    'kafr_el_dawar': 'Kafr El Dawar',
    'abu_hummus': 'Abu Hummus',
    'hosh_essa': 'Hosh Essa',
    'delengat': 'Delengat',
    'itay_el_barud': 'Itay El Barud',
    'shubrakhit': 'Shubrakhit',
    'edko': 'Edko',
    'rashid': 'Rashid',
    'rahmaniya': 'Rahmaniya',
    'noubaria': 'Noubaria',
    'kom_hamada': 'Kom Hamada',
    'abu_el_matamir': 'Abu El Matamir',
    'wadi_el_natrun': 'Wadi El Natrun',
    'advina': 'Advina',

    // Faiyum cities
    'faiyum_city': 'Faiyum City',
    'sinnuris': 'Sinnuris',
    'etsa': 'Etsa',
    'abubakk': 'Abubakk',
    'mosalla': 'Mosalla',

    // Gharbia cities
    'tanta': 'Tanta',
    'mahalla': 'Mahalla',
    'zefta': 'Zefta',
    'kafr_el_zayat': 'Kafr El Zayat',
    'basion': 'Basion',
    'qutour': 'Qutour',
    'santah': 'Santah',

    // Ismailia cities
    'ismailia_city': 'Ismailia City',
    'qantera_west': 'Qantera West',
    'tal_el_kebir': 'Tal El Kebir',
    'fayed': 'Fayed',
    'qantera': 'Qantera',
    'qantera_east': 'Qantera East',

    // Monufia cities
    'shebin_el_kom': 'Shebin El Kom',
    'menouf': 'Menouf',
    'ashmoun': 'Ashmoun',
    'bagour': 'Bagour',
    'sadat_city': 'Sadat City',
    'quesna': 'Quesna',
    'shohada': 'Shohada',
    'baranya': 'Baranya',
    'sadat': 'Sadat',
    'begeirm': 'Begeirm',
    'mit_bere': 'Mit Bere',
    'tala': 'Tala',
    'berket_el_sabaa': 'Berket El Sabaa',

    // Minya cities
    'minya_city': 'Minya City',
    'malawi': 'Malawi',
    'maghagha': 'Maghagha',
    'beni_mazar': 'Beni Mazar',
    'samalout': 'Samalout',
    'abu_qurqas': 'Abu Qurqas',
    'deir_mawas': 'Deir Mawas',
    'el_edwa': 'El Edwa',
    'matai': 'Matai',

    // Qalyubia cities
    'banha': 'Banha',
    'qalyub': 'Qalyub',
    'shubra_el_kheima': 'Shubra El Kheima',
    'kafr_shukr': 'Kafr Shukr',
    'tukh': 'Tukh',
    'shibin_el_qanater': 'Shibin El Qanater',
    'khanka': 'Khanka',
    'qaha': 'Qaha',
    'obour_city': 'Obour City',
    'khusus': 'Khusus',
    'qanatir': 'Qanatir',
    'abour': 'Abour',

    // New Valley cities
    'kharga': 'Kharga',
    'dakhla': 'Dakhla',
    'paris': 'Paris',

    // Suez cities
    'suez_city': 'Suez City',
    'arbaeen': 'Arbaeen',
    'suez_district': 'Suez District',
    'attaka_district': 'Attaka District',
    'el_ganayen_district': 'El Ganayen District',

    // Aswan cities
    'aswan_city': 'Aswan City',
    'kom_ombo': 'Kom Ombo',
    'daraw': 'Daraw',
    'new_aswan_city': 'New Aswan City',
    'edfu_center': 'Edfu Center',

    // Asyut cities
    'asyut_city': 'Asyut City',
    'abu_tis': 'Abu Tis',
    'nomiss': 'Nomiss',
    'abnub': 'Abnub',
    'dayrout': 'Dayrout',
    'manfalut': 'Manfalut',

    // Beni Suef cities
    'beni_suef_city': 'Beni Suef City',
    'wasta': 'Wasta',
    'naser': 'Naser',

    // Port Said cities
    'port_said_city': 'Port Said City',
    'port_fouad': 'Port Fouad',
    'east_district': 'East District',
    'west_district': 'West District',

    // Damietta cities
    'damietta_city': 'Damietta City',
    'faraskour': 'Faraskour',
    'kafr_saad': 'Kafr Saad',
    'zarqa': 'Zarqa',

    // Sharqia cities
    'zagazig': 'Zagazig',
    'belbeis': 'Belbeis',
    'abu_kabir': 'Abu Kabir',
    'kafr_saqr': 'Kafr Saqr',
    'menia_el_qamh': 'Menia El Qamh',
    'faques': 'Faques',
    'tenth_of_ramadan_city': 'Tenth of Ramadan City',
    'abu_hammad': 'Abu Hammad',
    'salheya': 'Salheya',
    'qanayat': 'Qanayat',
    'hehya': 'Hehya',
    'ibrahimia_sharqia': 'Ibrahimia Sharqia',
    'awlad_saqr': 'Awlad Saqr',
    'husseiniya': 'Husseiniya',
    'deirb_negm': 'Deirb Negm',
    'el_qurin': 'El Qurin',

    // South Sinai cities
    'sharm_el_sheikh': 'Sharm El Sheikh',
    'dahab': 'Dahab',
    'nuweiba': 'Nuweiba',

    // Kafr El Sheikh cities
    'kafr_el_sheikh_city': 'Kafr El Sheikh City',
    'desouk': 'Desouk',
    'sidi_salem': 'Sidi Salem',
    'fuwa': 'Fuwa',

    // Matrouh cities
    'marsa_matrouh': 'Marsa Matrouh',
    'north_coast': 'North Coast',
    'hacienda': 'Hacienda',
    'amwaj': 'Amwaj',
    'hamam': 'Hamam',
    'nagila': 'Nagila',
    'el_alamein': 'El Alamein',
    'dabaa': 'Dabaa',
    'sidi_barrani': 'Sidi Barrani',
    'salloum': 'Salloum',
    'siwa': 'Siwa',

    // Luxor cities
    'luxor_city': 'Luxor City',
    'esna': 'Esna',
    'qurna': 'Qurna',

    // Qena cities
    'qena_city': 'Qena City',
    'qift': 'Qift',
    'qous': 'Qous',
    'nag_hamadi': 'Nag Hamadi',
    'deshna': 'Deshna',
    'naqada': 'Naqada',

    // North Sinai cities
    'el_arish': 'El Arish',
    'sheikh_zuweid': 'Sheikh Zuweid',
    'rafah': 'Rafah',

    // Sohag cities
    'sohag_city': 'Sohag City',
    'girga': 'Girga',
    'tahta': 'Tahta',
    'asierat': 'Asierat',
    'akhmim': 'Akhmim',
};

export const getGovernorateName = (key) => {
    if (!key) return 'N/A';
    return governorateMap[key.toLowerCase()] || key;
};

export const getCityName = (key) => {
    if (!key) return 'N/A';
    return cityMap[key.toLowerCase()] || key;
};
