export const serviceMappings = {
    // Services / Categories
    "human_hospital": "Human Hospital or Medical Center",
    "human_doctor": "Human Doctor",
    "human_pharmacy": "Human Pharmacy or Medical Supplies",
    "lab": "Laboratory",
    "radiology_center": "Radiology Center",
    "optics": "Optics",
    "gym": "Gym or Sports Academy",
    "veterinary_hospital": "Veterinary Hospital or Center",
    "veterinarian": "Veterinarian",
    "veterinary_pharmacy": "Veterinary Pharmacy or Animal Supplies",

    // Specializations
    "all_specializations": "All Specializations",
    "dermatology": "Dermatology",
    "laser": "Laser",
    "dentistry": "Dentistry",
    "hair_transplant": "Hair Transplant",
    "psychiatry": "Psychiatry",
    "pediatrics_neonatology": "Pediatrics & Neonatology",
    "neurology": "Neurology",
    "orthopedics": "Orthopedics",
    "obstetrics_gynecology": "Obstetrics & Gynecology",
    "ent": "ENT",
    "cardiology": "Cardiology & Vascular",
    "internal_medicine": "Internal Medicine",
    "interventional_radiology": "Interventional Radiology",
    "hematology": "Hematology",
    "oncology": "Oncology",
    "nutrition_weight_loss": "Nutrition & Weight Loss",
    "pediatric_surgery": "Pediatric Surgery",
    "surgical_oncology": "Surgical Oncology",
    "vascular_surgery": "Vascular Surgery",
    "plastic_surgery": "Plastic Surgery",
    "bariatric_surgery": "Bariatric & Endoscopic Surgery",
    "general_surgery": "General Surgery",
    "spine_surgery": "Spine Surgery",
    "cardio_thoracic_surgery": "Cardio-Thoracic Surgery",
    "neurosurgery": "Neurosurgery",
    "gastroenterology_endoscopy": "Gastroenterology & Endoscopy",
    "allergy_immunology": "Allergy & Immunology",
    "ivf": "IVF & Infertility",
    "andrology_infertility": "Andrology & Infertility",
    "rheumatology": "Rheumatology",
    "endocrinology": "Endocrinology & Diabetes",
    "audiology": "Audiology",
    "pulmonology": "Pulmonology & Respiratory",
    "family_medicine": "Family Medicine",
    "geriatrics": "Geriatrics",
    "rehabilitative_medicine": "Rehabilitative Medicine",
    "pain_management": "Pain Management",
    "physiotherapy_sports": "Physiotherapy & Sports Injuries",
    "ophthalmology": "Ophthalmology",
    "hepatology": "Hepatology",
    "nephrology": "Nephrology",
    "urology": "Urology",
    "general_practice": "General Practice",
    "speech_therapy": "Speech Therapy",

    // Discounts
    "enter_discount_on_other_services": "Enter discount on other services",
    "enter_price_before_discount": "Enter price before discount",
    "enter_price_after_discount": "Enter price after discount",
    "home_visit": "Is there a home visit?",
    "is_home_visit": "Is there a home visit?",
    "is_home_card": "Can the discount card be used in case of a home visit?",
    "Can_the_discount_card_be_used_in_the_case_of_a_home_visit": "Can the discount card be used in case of a home visit?",
    "home_discount": "Can the discount card be used in case of a home visit?",
    "home_delivery": "Is there home delivery?",
    "is_home_delivery": "Is there home delivery?",
    "is_delivery": "Is there home delivery?",
    "Can_the_discount_card_be_used_in_the_case_of_a_home_delivery": "Can the discount card be used in case of home delivery?",
    "pharmacy_is_home_card": "Can the discount card be used in case of home delivery?",
    "is_home_service": "Is there home service?",
    "eye_care_is_card": "Can the discount card be used in case of home delivery?",
    "Home_service_available": "Is there a home visit?",
    "home_service": "Is there home service?",
    "canUseDiscountCard": "The discount card can be used in case of a home visit",
    "accept_insurance": "Accept Insurance",
    "consultation_price_before_discount": "Consultation Price Before Discount",
    "consultation_price_after_discount": "Consultation Price After Discount",
    "examinations_discount": "Examinations Discount",
    "medical_tests_discount": "Medical Tests Discount",
    "xray_discount": "X-Ray Discount",
    "medicines_discount": "Medicines Discount",
    "local_medicines_discount": "Local Medicines Discount",
    "imported_medicines_discount": "Imported Medicines Discount",
    "medical_supplies_discount": "Medical Supplies Discount",
    "all_tests_discount": "All Tests Discount",
    "other_discount": "Other Discount",
    "glasses_discount": "Glasses Discount",
    "sunglasses_discount": "Sunglasses Discount",
    "contact_lenses_discount": "Contact Lenses Discount",
    "eye_exam_discount": "Eye Exam Discount",
    "surgeries_other_services_discount": "Discount on Surgeries or Other Services",
    "enter_surgeries_other_services_discount": "Enter discount on surgeries or other services",
    "consultation_price_before": "Consultation Price Before Discount",
    "consultation_price_after": "Consultation Price After Discount",

    // Gym Subscriptions
    "1_month_subscription": "1 Month Subscription",
    "3_months_subscription": "3 Months Subscription",
    "6_months_subscription": "6 Months Subscription",
    "12_months_subscription": "12 Months Subscription",
    "price_before": "Price Before",
    "price_after": "Price After",
    "discount_on_other_services": "Discount on Other Services",
    "gym_month_sub_price_b": "1 Month Subscription Price Before Discount",
    "gym_month_sub_price_a": "1 Month Subscription Price After Discount",
    "gym_month_3_sub_price_b": "3 Months Subscription Price Before Discount",
    "gym_month_3_sub_price_a": "3 Months Subscription Price After Discount",
    "gym_month_6_sub_price_b": "6 Months Subscription Price Before Discount",
    "gym_month_6_sub_price_a": "6 Months Subscription Price After Discount",
    "gym_month_12_sub_price_b": "12 Months Subscription Price Before Discount",
    "gym_month_12_sub_price_a": "12 Months Subscription Price After Discount",
};

export const getMappedValue = (key) => {
    return serviceMappings[key] || key;
};
