import React, { createContext, useContext, useState, useEffect } from 'react';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// Translation files (To be filled)
const resources = {
    en: {
        translation: {
            "welcome": "Welcome back!",
            "search": "Search anything here...",
            "services": "Services",
            "customers": "Customers",
            "videos": "Videos",
            "member_since": "Member since",
            "no_active_subscription": "NO ACTIVE SUBSCRIPTION",
            "active_subscription": "ACTIVE SUBSCRIPTION",
            "subscription_expired": "SUBSCRIPTION EXPIRED",
            "expiring_soon": "EXPIRING SOON",
            "active": "ACTIVE",
            "inactive": "INACTIVE",
            "expired": "EXPIRED",
            "logout": "Logout",
            "change_password": "Change Password",
            "light_mode": "Light Mode",
            "dark_mode": "Dark Mode",
            "switch_to_arabic": "Switch to Arabic",
            "switch_to_english": "Switch to English",
            "full_name": "FULL NAME",
            "email_address": "EMAIL ADDRESS",
            "phone_number": "PHONE NUMBER",
            "contact_information": "Contact Information",
            "subscription_status": "Subscription Status",
            "family_members": "Family Members",
            "id": "ID",
            "personal_promo_code": "Personal Promo Code",
            "activate_subscription": "Activate Subscription",
            "approve": "Approve",
            "cancel": "Cancel",
            "valid_until": "Valid Until",
            "expired_on": "Expired On",
            "days_remaining": "Days Remaining",
            "days": "days",
            "no_family_members": "No family members added yet",
            "member": "Member",
            "members": "Members",
            "mother": "Mother",
            "father": "Father",
            "son": "Son",
            "daughter": "Daughter",
            "wife": "Wife",
            "husband": "Husband",
            "sister": "Sister",
            "brother": "Brother",
            "pet": "Pet",
            "human": "Human",
            "customer_details": "Customer Details",
            "manage_customer_info": "View and manage customer information for",
            "customer_name": "Customer Name",
            "email": "Email",
            "phone_number": "Phone Number",
            "subscription": "Subscription",
            "promo_code": "Promo Code",
            "actions": "Actions",
            "total_count": "Total Count",
            "all_customers": "All Customers",
            "not_subscribed": "Not Subscribed",
            "subscribed": "Subscribed",
            "activate": "Activate",
            "activated": "Activated",
            "no_code": "No Code",
            "click_to_copy": "Click to copy",
            "copied": "Copied!",
            "promo_code_copied": "Promo code \"{{code}}\" copied to clipboard",
            "n_a": "N/A",
            "view_details": "View Details",
            "provider_info": "Provider Info",
            "provider_phone": "Provider Phone",
            "service_name": "Service Name",
            "created_at": "Created At",
            "status": "Status",
            "actions": "Actions",
            "all_services": "All Services",
            "approved": "Approved",
            "rejected": "Rejected",
            "pending": "Pending",
            "approve_service_title": "Approve Service",
            "approve_service_desc": "Are you sure you want to approve this service?",
            "reject_service_title": "Reject Service",
            "reject_service_desc": "Are you sure you want to reject this service?",
            "service_details": "Service Details",
            "manage_service_info": "View and manage service information for",
            "reject": "Reject",
            "about_service": "About the Service",
            "no_description": "No description provided for this service.",
            "additional_specs": "Additional Service Specs",
            "provider_contact_details": "Provider Contact Details",
            "provider_social_media": "Provider Social Media",
            "no_social_links": "No social media links provided",
            "service_branches": "Service Branches",
            "no_branches": "No branches available",
            "branches_count_one": "1 Branch Available",
            "branches_count_other": "{{count}} Branches Available",
            "branch_number": "Branch #{{number}}",
            "location": "Location",
            "contact": "Contact",
            "view_on_map": "View on Map",
            "working_hours": "Working Hours",
            "closed": "Closed",
            "sun": "Sun",
            "mon": "Mon",
            "tue": "Tue",
            "wed": "Wed",
            "thu": "Thu",
            "fri": "Fri",
            "sat": "Sat",
            "yes": "Yes",
            "no": "No",
            "approve_service_desc_name": "Are you sure you want to approve \"{{name}}\"?",
            "reject_service_desc_name": "Are you sure you want to reject \"{{name}}\"?",
            "submitted": "Submitted",
            "delivery_availability": "Home Delivery Availability",
            "delivery": "Delivery",
            "discount_card_usage": "Discount Card Usage",
            "discount_card": "Discount Card",
            "login": "Login",
            "email_label": "Email",
            "password_label": "Password",
            "enter_email": "Enter Admin Email",
            "enter_password": "Enter Admin Password",
            "login_success": "Login successful",
            "login_failed": "Login Failed",
            "upload_new_video": "Upload New Video",
            "all_videos": "All Videos",
            "top_section": "Top Section",
            "bottom_section": "Bottom Section",
            "no_videos_yet": "No Videos Yet",
            "upload_first_video_desc": "Upload your first video to get started",
            "upload_video": "Upload Video",
            "description": "Description",
            "delete_video": "Delete Video",
            "top": "Top",
            "bottom": "Bottom",
            "delete_video_title": "Delete Video",
            "delete_video_desc": "Are you sure you want to delete this video? This action cannot be undone.",
            "no_cancel": "No, Cancel",
            "video_file": "Video File",
            "select_video_file": "Select video file",
            "enter_video_description": "Enter video description",
            "video_position": "Video Position",
            "video_position_desc": "Choose where this video will appear in the mobile app",
            "top_section_desc": "Video will appear at the top of the list",
            "bottom_section_desc": "Video will appear at the bottom of the list",
            "video_uploaded_title": "Video Uploaded",
            "video_uploaded_desc": "Your video has been uploaded successfully.",
            "error_uploading_video": "Error uploading video",
            "includes_number": "Includes number",
            "includes_lowercase": "Includes lowercase letter",
            "includes_uppercase": "Includes uppercase letter",
            "includes_special_symbol": "Includes special symbol",
            "password_changed_title": "Password Changed",
            "password_changed_desc": "Your password has been changed successfully.",
            "error_changing_password": "Error resetting password",
            "current_password": "Current Password",
            "new_password": "New Password",
            "confirm_password": "Confirm Password",
            "admin": "Admin",
            "admin_initials": "AD",
            "logging_out": "Logging out...",
            "delete": "Delete",
            "success": "Success",
            "error": "Error",
            "warning": "Warning",
            "info": "Info",
            "operation_success": "Operation completed successfully",
            "something_went_wrong": "Something went wrong",
            "use_larger_screen": "Please Use a Larger Screen",
            "larger_screen_desc": "This dashboard is optimized for larger screens. Please switch to a PC or tablet for the best experience.",
            "mobile_view_not_supported": "Mobile view is not supported at this time.",
            "app_name": "Alligny",
            "app_tagline": "let’s start the journey.",
            "uploaded": "Uploaded",
            "uploaded_by": "Uploaded By",
            "file_size": "File Size",
            "format": "Format",
            "position": "Position",
            "top_section_full": "↑ Top Section",
            "bottom_section_full": "↓ Bottom Section",
            "subscription_activated_title": "Subscription Activated",
            "subscription_activated_desc": "Customer subscription has been activated successfully.",
            "error_activating_subscription": "Error activating subscription",
            "service_approved_success": "Service approved successfully",
            "service_rejected_success": "Service rejected successfully",
            "failed_to_perform_action": "Failed to perform action",
            "activate_subscription_desc": "Are you sure you want to activate subscription for this customer?",
            "video_deleted_success": "Video has been deleted successfully.",
            "error_deleting_video": "Error deleting video",
            "email_required": "Email is required",
            "invalid_email": "Please enter a valid email address",
            "password_required": "Password is required",
            "password_min_length": "Password must be at least {{count}} characters",
            "password_max_length": "Password cannot exceed {{count}} characters",
            "password_lowercase": "Password must contain at least one lowercase letter",
            "password_uppercase": "Password must contain at least one uppercase letter",
            "password_number": "Password must contain at least one number",
            "password_special": "Password must contain at least one special character (@$!%*?&#)",
            "current_password_required": "Current password is required",
            "new_password_required": "New password is required",
            "new_password_same_as_current": "New password cannot be the same as current password",
            "confirm_password_required": "Please confirm your new password",
            "passwords_match": "Passwords must match",
            "video_required": "Video file is required",
            "max_file_size": "File size must be less than 50MB",
            "video_file_only": "Only video files are allowed",
            "description_required": "Description is required",
            "description_min": "Description must be at least {{count}} characters",
            "description_max": "Description must not exceed {{count}} characters",
            "video_position_required": "Video position is required",
            "invalid_position": "Please select either Top or Bottom section",
            "not_found_title": "Oops! You're lost.",
            "not_found_desc": "The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.",
            "return_home": "Return Home"
        }
    },
    ar: {
        translation: {
            "welcome": "أهلاً بك مجدداً!",
            "search": "ابحث عن أي شيء هنا...",
            "services": "الخدمات",
            "customers": "العملاء",
            "videos": "الفيديوهات",
            "member_since": "عضو منذ",
            "no_active_subscription": "لا يوجد اشتراك نشط",
            "active_subscription": "اشتراك نشط",
            "subscription_expired": "انتهى الاشتراك",
            "expiring_soon": "ينتهي قريباً",
            "active": "نشط",
            "inactive": "غير نشط",
            "expired": "منتهي",
            "logout": "تسجيل الخروج",
            "change_password": "تغيير كلمة المرور",
            "light_mode": "الوضع الفاتح",
            "dark_mode": "الوضع الليلي",
            "switch_to_arabic": "التبديل إلى العربية",
            "switch_to_english": "التبديل إلى الإنجليزية",
            "full_name": "الاسم الكامل",
            "email_address": "البريد الإلكتروني",
            "phone_number": "رقم الهاتف",
            "contact_information": "معلومات الاتصال",
            "subscription_status": "حالة الاشتراك",
            "family_members": "أفراد العائلة",
            "id": "المعرف",
            "personal_promo_code": "كود الخصم الشخصي",
            "activate_subscription": "تفعيل الاشتراك",
            "approve": "موافقة",
            "cancel": "إلغاء",
            "valid_until": "صالح حتى",
            "expired_on": "انتهى في",
            "days_remaining": "الأيام المتبقية",
            "days": "أيام",
            "no_family_members": "لم يتم إضافة أفراد عائلة بعد",
            "member": "عضو",
            "members": "أعضاء",
            "mother": "الأم",
            "father": "الأب",
            "son": "الابن",
            "daughter": "الابنة",
            "wife": "الزوجة",
            "husband": "الزوج",
            "sister": "الأخت",
            "brother": "الأخ",
            "pet": "حيوان أليف",
            "human": "إنسان",
            "customer_details": "تفاصيل العميل",
            "manage_customer_info": "عرض وإدارة معلومات العميل لـ",
            "customer_name": "اسم العميل",
            "email": "البريد الإلكتروني",
            "phone_number": "رقم الهاتف",
            "subscription": "الاشتراك",
            "promo_code": "كود الخصم",
            "actions": "الإجراءات",
            "total_count": "العدد الإجمالي",
            "all_customers": "جميع العملاء",
            "not_subscribed": "غير مشترك",
            "subscribed": "مشترك",
            "activate": "تفعيل",
            "activated": "تم التفعيل",
            "no_code": "لا يوجد كود",
            "click_to_copy": "انقر للنسخ",
            "copied": "تم النسخ!",
            "promo_code_copied": "تم نسخ كود الخصم \"{{code}}\" إلى الحافظة",
            "n_a": "غير متوفر",
            "view_details": "عرض التفاصيل",
            "provider_info": "معلومات المزود",
            "provider_phone": "هاتف المزود",
            "service_name": "اسم الخدمة",
            "created_at": "تاريخ الإنشاء",
            "status": "الحالة",
            "all_services": "جميع الخدمات",
            "approved": "مقبول",
            "rejected": "مرفوض",
            "pending": "معلق",
            "approve_service_title": "قبول الخدمة",
            "approve_service_desc": "هل أنت متأكد أنك تريد قبول هذه الخدمة؟",
            "reject_service_title": "رفض الخدمة",
            "reject_service_desc": "هل أنت متأكد أنك تريد رفض هذه الخدمة؟",
            "service_details": "تفاصيل الخدمة",
            "manage_service_info": "عرض وإدارة معلومات الخدمة لـ",
            "reject": "رفض",
            "about_service": "عن الخدمة",
            "no_description": "لا يوجد وصف لهذه الخدمة حالياً.",
            "additional_specs": "مواصفات الخدمة الإضافية",
            "provider_contact_details": "بيانات الاتصال بمزود الخدمة",
            "provider_social_media": "وسائل التواصل الاجتماعي للمزود",
            "no_social_links": "لا توجد روابط تواصل اجتماعي",
            "service_branches": "فروع الخدمة",
            "no_branches": "لا توجد فروع متاحة لهذه الخدمة",
            "branches_count_one": "فرع واحد متاح",
            "branches_count_two": "فرعان متاحان",
            "branches_count_few": "{{count}} فروع متاحة",
            "branches_count_many": "{{count}} فرعاً متاحاً",
            "branches_count_other": "{{count}} فرع متاح",
            "branch_number": "فرع رقم {{number}}",
            "location": "الموقع",
            "contact": "الاتصال",
            "view_on_map": "عرض على الخريطة",
            "working_hours": "ساعات العمل",
            "closed": "مغلق",
            "sun": "الأحد",
            "mon": "الاثنين",
            "tue": "الثلاثاء",
            "wed": "الأربعاء",
            "thu": "الخميس",
            "fri": "الجمعة",
            "sat": "السبت",
            "yes": "نعم",
            "no": "لا",
            "approve_service_desc_name": "هل أنت متأكد من قبول \"{{name}}\"؟",
            "reject_service_desc_name": "هل أنت متأكد من رفض \"{{name}}\"؟",
            "submitted": "تم الإرسال",
            "delivery_availability": "توفر خدمة التوصيل",
            "delivery": "التوصيل",
            "discount_card_usage": "استخدام كارت الخصم",
            "discount_card": "كارت الخصم",
            "login": "تسجيل الدخول",
            "email_label": "البريد الإلكتروني",
            "password_label": "كلمة المرور",
            "enter_email": "أدخل البريد الإلكتروني للمسؤول",
            "enter_password": "أدخل كلمة المرور للمسؤول",
            "login_success": "تم تسجيل الدخول بنجاح",
            "login_failed": "فشل تسجيل الدخول",
            "upload_new_video": "رفع فيديو جديد",
            "all_videos": "جميع الفيديوهات",
            "top_section": "القسم العلوي",
            "bottom_section": "القسم السفلي",
            "no_videos_yet": "لا توجد فيديوهات بعد",
            "upload_first_video_desc": "قم برفع أول فيديو لتظهر هنا",
            "upload_video": "رفع فيديو",
            "description": "الوصف",
            "delete_video": "حذف الفيديو",
            "top": "الأعلى",
            "bottom": "الأسفل",
            "delete_video_title": "حذف الفيديو",
            "delete_video_desc": "هل أنت متأكد من حذف هذا الفيديو؟ لا يمكن التراجع عن هذا الإجراء.",
            "no_cancel": "لا، إلغاء",
            "video_file": "ملف الفيديو",
            "select_video_file": "اختر ملف الفيديو",
            "enter_video_description": "أدخل وصف الفيديو",
            "video_position": "موقع الفيديو",
            "video_position_desc": "اختر مكان ظهور هذا الفيديو في تطبيق الموبايل",
            "top_section_desc": "سيظهر الفيديو في أعلى القائمة",
            "bottom_section_desc": "سيظهر الفيديو في أسفل القائمة",
            "video_uploaded_title": "تم رفع الفيديو",
            "video_uploaded_desc": "تم رفع الفيديو الخاص بك بنجاح.",
            "error_uploading_video": "خطأ في رفع الفيديو",
            "includes_number": "يحتوي على رقم",
            "includes_lowercase": "يحتوي على حرف صغير",
            "includes_uppercase": "يحتوي على حرف كبير",
            "includes_special_symbol": "يحتوي على رمز خاص",
            "password_changed_title": "تم تغيير كلمة المرور",
            "password_changed_desc": "تم تغيير كلمة المرور الخاصة بك بنجاح.",
            "error_changing_password": "خطأ في إعادة تعيين كلمة المرور",
            "current_password": "كلمة المرور الحالية",
            "new_password": "كلمة المرور الجديدة",
            "confirm_password": "تأكيد كلمة المرور الجديدة",
            "admin": "المسؤول",
            "admin_initials": "م",
            "logging_out": "جاري تسجيل الخروج...",
            "delete": "حذف",
            "success": "تم بنجاح",
            "error": "خطأ",
            "warning": "تحذير",
            "info": "تنبيه",
            "operation_success": "تمت العملية بنجاح",
            "something_went_wrong": "حدث خطأ ما",
            "use_larger_screen": "يرجى استخدام شاشة أكبر",
            "larger_screen_desc": "هذه اللوحة مطورة للشاشات الكبيرة. يرجى استخدام جهاز كمبيوتر أو تابلت للحصول على أفضل تجربة.",
            "mobile_view_not_supported": "عرض الموبايل غير مدعوم حالياً.",
            "app_name": "عالجني",
            "app_tagline": "فلنبدأ الرحلة.",
            "uploaded": "تم الرفع في",
            "uploaded_by": "بواسطة",
            "file_size": "حجم الملف",
            "format": "الصيغة",
            "position": "الموقع",
            "top_section_full": "↑ القسم العلوي",
            "bottom_section_full": "↓ القسم السفلي",
            "subscription_activated_title": "تم تفعيل الاشتراك",
            "subscription_activated_desc": "تم تفعيل اشتراك العميل بنجاح.",
            "error_activating_subscription": "خطأ في تفعيل الاشتراك",
            "service_approved_success": "تم قبول الخدمة بنجاح",
            "service_rejected_success": "تم رفض الخدمة بنجاح",
            "failed_to_perform_action": "فشل تنفيذ الإجراء",
            "activate_subscription_desc": "هل أنت متأكد من تفعيل الاشتراك لهذا العميل؟",
            "video_deleted_success": "تم حذف الفيديو بنجاح.",
            "error_deleting_video": "خطأ في حذف الفيديو",
            "email_required": "البريد الإلكتروني مطلوب",
            "invalid_email": "يرجى إدخال بريد إلكتروني صحيح",
            "password_required": "كلمة المرور مطلوبة",
            "password_min_length": "يجب أن تكون كلمة المرور {{count}} أحرف على الأقل",
            "password_max_length": "لا يمكن أن تتجاوز كلمة المرور {{count}} حرفاً",
            "password_lowercase": "يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل",
            "password_uppercase": "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل",
            "password_number": "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
            "password_special": "يجب أن تحتوي كلمة المرور على رمز خاص واحد على الأقل (@$!%*?&#)",
            "current_password_required": "كلمة المرور الحالية مطلوبة",
            "new_password_required": "كلمة المرور الجديدة مطلوبة",
            "new_password_same_as_current": "لا يمكن أن تكون كلمة المرور الجديدة هي نفسها كلمة المرور الحالية",
            "confirm_password_required": "يرجى تأكيد كلمة المرور الجديدة",
            "passwords_match": "كلمات المرور غير متطابقة",
            "video_required": "ملف الفيديو مطلوب",
            "max_file_size": "يجب أن يكون حجم الملف أقل من 50 ميجابايت",
            "video_file_only": "مسموح بملفات الفيديو فقط",
            "description_required": "الوصف مطلوب",
            "description_min": "يجب أن يكون الوصف {{count}} أحرف على الأقل",
            "description_max": "يجب ألا يتجاوز الوصف {{count}} حرفاً",
            "video_position_required": "موقع الفيديو مطلوب",
            "invalid_position": "يرجى اختيار القسم العلوي أو السفلي",
            "not_found_title": "عفواً! لقد تهت.",
            "not_found_desc": "قد تكون الصفحة التي تبحث عنها قد تمت إزالتها، أو تم تغيير اسمها، أو أنها غير متاحة مؤقتاً.",
            "return_home": "العودة للرئيسية"
        }
    }
};

i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        resources,
        fallbackLng: 'en',
        interpolation: {
            escapeValue: false
        }
    });

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(i18n.language || 'en');

    const changeLanguage = (lng) => {
        i18n.changeLanguage(lng);
        setLanguage(lng);
    };

    useEffect(() => {
        const dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.dir = dir;
        document.documentElement.lang = language;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, changeLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
